---
title: "Data"
fig-cap-location: "bottom"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
suppressPackageStartupMessages(require(knitr))
suppressPackageStartupMessages(require(kableExtra))
suppressPackageStartupMessages(require(dplyr))
suppressPackageStartupMessages(require(ggplot2))
suppressPackageStartupMessages(require(plotly))
suppressPackageStartupMessages(require(tidyr))
options(warn = -1)
```


Los datos de precipitación diaria (Kg m-2 s-1) son productos de modelos regionales. Para este trabajo se obtuvieron desde la página web del Coordinated Regional Climate Downscaling Experiment. Para ello, se realizó previamente una inspección de la disponibilidad de diferentes modelos de dominio sudamericano (desde 19°N a 52°S y desde 105° a 17°O). El dominio sudamericano contempla tres resoluciones espaciales horizontales; SAM-20 (0.20°x0.20°), SAM-22 (0.22°x0.22°) y SAM- 44 (0.44°x0.44°). Debido a que el objetivo de este trabajo se enmarca en observar las tendencias de los dry spells en los tres escenarios del cambio climático, se determinó trabajar con el dominio SAM-44, el único que considera los tres escenarios. Se utilizaron tres Driving Models de precipitación diaria del dominio SAM-44 y los tres escenarios RCP (2.6, 4.5 y 8.5); MIROC-MIROC5, ICHEC- EC-EARTH y MOHC-HadGEM2-ES.

