# Prefacio {.unnumbered}

El presente libro digital tiene como objetivo documentar y explicar de forma detallada el los análisis realizados para el proyecto final del curso de _Ciencia de Datos para el Análisis de Cambio Climático_. El tema principal del presente documento es **Análisis de cambio de probabilidad de “Dry Spells” en la zona centro de Chile bajo cambio climático**


## Alumnos:
Denis Berroeta1,2, José Miguel Cerda-Paredes2,3, Vicente Vega4

1 Centro de Inteligencia Territorial, Universidad Adolfo Ibáñez, Av. Presidente Errázuriz 3485, Chile. 
2. Programa de Doctorado en Data Science, Facultad de Ingeniería y Ciencias, Universidad Adolfo Ibáñez. Diagonal Las Torres 2640, Santiago, Chile.
3. Fundación Data Observatory. Eliodoro Yáñez 2990, Santiago, Chile.
4. Programa de Magister en Ciencias de la Ingeniería, Facultad de Ingeniería y Ciencias, Universidad Adolfo Ibáñez. Diagonal Las Torres 2640, Santiago, Chile.

TODO:

- Solicitar las imagenes y referencias
- agregar iamgenes y referencias
- agregar referencias bibliogràficas
- agregar códigos a repositorio
- agregar material suplementario