# Introducción

La zona Mediterránea de Chile se distribuye entre los 25° y 40°S, específicamente entre las regiones de Atacama y la Araucanía (Pliscoff & Luebert, 2022). En esta zona se han registrado precipitaciones promedio fluctuantes, entre 100 y 1000 mm, dependiendo de la latitud y altitud. De esta forma se producen 2 tipos de climas característicos de Chile central; un clima Mediterráneo y otro semiárido (CR2, 2021).

En la zona Mediterránea chilena no ocurren tormentas con alta frecuencia. La ocurrencia de fenómenos de precipitación extrema ocurre con una frecuencia promedio de una cada 10 años. Generalmente, de uno o dos días de duración, con cerca de un 90 % de la lluvia cayendo entre los meses de abril a septiembre (CR2, 2021). Las precipitaciones pueden verse afectadas por distintos factores, como las oscilaciones inter decadales, la oscilación decadal del Pacífico que aumenta la temperatura superficial del mar o bien las oscilaciones interanuales, como lo son el fenómeno de La Niña o El Niño, e incluso fenómenos intra estacionales (CR2, 2021). Entre los factores que tienen estrecha relación con la precipitación están las altas temperaturas por un tiempo prolongado que supera las duraciones normales, estas son llamadas olas de calor. Las olas de calor son fenómenos climáticos extremos en los sistemas atmosféricos y oceánicos que pueden tener efectos devastadores y a largo plazo en los ecosistemas, con las consiguientes consecuencias socioeconómicas (Oliver et al., 2018). El mantenimiento de olas de calor en un sistema puede llegar a generar fenómenos propios de sequía o inclusive en una forma más extrema, mega sequías.

Las sequías y mega sequías son fenómenos que son influenciadas por múltiples factores; anomalías de la temperatura superficial del mar, las retroalimentaciones tierra-atmósfera, la variabilidad atmosférica interna y fuerzas externas (Lin et al., 2022). Los fenómenos de sequía o mega sequía son distinguibles por la disminución de recursos hídricos presentes enfuentes acuíferas y cuencas hidrográficas, donde disminuyen además los reservorios de agua en forma de aguanieve y asimismo de las precipitaciones por un tiempo prolongado (Garreaud, 2017). Las sequías no sólo se atribuyen a la disminución en la cantidad de precipitación, sino también al aumento en la duración de los períodos secos o dry spells. Estos son los periodos entre lluvias, es decir, desde que deja de llover hasta que comienza a llover nuevamente. La variabilidad en la cantidad de lluvia diaria puede manifestarse en períodos prolongados de condiciones húmedas o secas, lo cual resulta útil para comprender el impacto de la concentración de precipitaciones. Los índices más comúnmente utilizados para analizar las características de los períodos secos y húmedos incluyen el número de períodos, la duración promedio de estos y la duración máxima de los períodos (Ratan & Venugopal, 2013; Şen et al., 2020).


Según Wainwright et al. (2022) las proyecciones indican que los dry spells más largos aumentarían en frecuencia en Sudamérica. Al igual que López-Franca et al. (2015) que proponen un fuerte aumento en la probabilidad de ocurrencia de períodos secos largos y disminución de la probabilidad de ocurrencia de períodos secos cortos en regiones Mediterráneas. La prolongación de los dry spells alcanzarían aproximadamente 2 días más por década en Sudamérica y África meridional (Wainwright et al., 2022). Esto coincide con Polade et al. (2014) quienes estiman hasta 30 días secos más al año podrían experimentar Sudamérica y las regiones Mediterráneas, a finales de este siglo. Estas proyecciones muestran patrones cualitativamente coherentes con los futuros cambios previstos en el escenario del cambio climático. La prolongación de los periodos de sequía en Sudamérica está asociada al calentamiento relativo de las temperaturas de la superficie marina del Atlántico Norte y a la amplificación del calentamiento terrestre en comparación con los océanos adyacentes; se prevé que ambos fenómenos continúen con un mayor calentamiento, lo que sugiere la existencia de un impulsor común de las tendencias recientes y las proyecciones futuras (Polade et al., 2014; Wainwright et al. 2022).



Los dry spells pueden implicar un peligro para el lugar en el que se desarrollan, no solo por la disminución de recursos hídricos, sino por posibles eventos extremos posteriores al periodo seco. Esto se explica ya que en dicho lugar comienza a evolucionar un proceso de acumulación de distribución de precipitación, es decir, lo que debiese haber llovido durante el periodo seco se acumula y precipita adicionalmente en otro momento, generando una precipitación intensa en un periodo acotado de tiempo (Martinez-villalobos & Neelin, 2017). Si bien, se han analizado fenómenos de sequía en presencia de dry spells, la crisis climática es una variable relevante en cuanto al análisis de fenómenos climatológicos, más aún en cuanto a zonas chilenas en situación de alta vulnerabilidad climática (IPCC, 2022). Por lo que establecer un análisis que permita proyectar eventos futuros implica evitar pérdidas de recursos naturales, principalmente hídricos, así como logísticos y económicos.

El objetivo de este trabajo es determinar cómo cambia la probabilidad de ocurrencia de dry spells en la zona centro de Chile bajo escenarios de cambio climático proyectado para las próximas décadas. Se busca entender cómo las tendencias actuales en la variabilidad climática en la zona Mediterránea pueden afectar la duración y frecuencia de los períodos de sequía. Para ello se utilizaron datos diarios de precipitación históricos, así como también proyecciones futuras en tres escenarios del cambio climático de tres modelos regionales. Se definió un umbral y se calculó la duración y frecuencia de dry spells en la zona Mediterránea de Chile.

Este trabajo presenta una estructura por secciones; la sección Data explica la obtención de datos de cada modelo utilizado, luego la sección Métodos donde se profundiza en el procesamiento de los datos para determinar parámetros de los dry spells. Finalmente, dos secciones; Resultados y Conclusiones donde se presentarán los productos obtenidos y las conclusiones propuestas.


